/**
 * src/renderer/dom.js
 * DOM operations
 */

import { MSG } from "../shared/protocol.js";

/**
 * Normalize a vnode children array by removing null children.
 * The compiler may generate null for missing conditional branches.
 * @param {Array<object | null> | null | undefined} children
 * @returns {object[]}
 */
export function normalizeChildren(children) {
  return (children || []).filter((child) => child != null);
}

/**
 * Remove one prop from a DOM element.
 * @param {HTMLElement} el
 * @param {string} key
 * @returns {void}
 */
function removeProp(el, key) {
  if (key === "class") {
    el.className = "";
    return;
  }

  if (key === "style") {
    el.style.cssText = "";
    return;
  }

  el.removeAttribute(key);
}

/**
 * Set one prop onto a DOM element.
 * @param {HTMLElement} el
 * @param {string} key
 * @param {any} value
 * @returns {void}
 */
function setProp(el, key, value) {
  if (value == null) {
    removeProp(el, key);
    return;
  }

  if (key === "class") {
    el.className = String(value);
    return;
  }

  if (key === "style") {
    el.style.cssText = "";

    if (value && typeof value === "object") {
      Object.assign(el.style, value);
    } else {
      el.style.cssText = String(value);
    }

    return;
  }

  el.setAttribute(key, String(value));
}

/**
 * Set all properties onto a DOM element.
 * @param {HTMLElement} el
 * @param {object} props
 * @returns {void}
 */
export function setProps(el, props = {}) {
  for (const key of Object.keys(props)) {
    setProp(el, key, props[key]);
  }
}

/**
 * Patch element properties from oldProps to newProps.
 * @param {HTMLElement} el
 * @param {object} oldProps
 * @param {object} newProps
 * @returns {void}
 */
export function patchProps(el, oldProps = {}, newProps = {}) {
  for (const key of Object.keys(newProps)) {
    if (oldProps[key] !== newProps[key]) {
      setProp(el, key, newProps[key]);
    }
  }

  for (const key of Object.keys(oldProps)) {
    if (!(key in newProps)) {
      removeProp(el, key);
    }
  }
}

/**
 * Bind runtime events for a vnode.
 * Current event model:
 * - only button supports click
 * - vnode.event is treated as the handler name string generated by compiler
 * @param {HTMLElement} el
 * @param {object} vnode
 * @param {Worker} worker
 * @returns {void}
 */
export function bindEvents(el, vnode, worker) {
  if (vnode.type !== "button") {
    return;
  }

  if (!vnode.event) {
    el.onclick = null;
    return;
  }

  el.onclick = () => {
    worker.postMessage({
      type: MSG.EVENT,
      name: vnode.event,
      payload: {},
    });
  };
}

/**
 * Create a DOM node from a vnode and store vnode.el.
 * Current tag mapping:
 * - #text  -> Text
 * - view   -> div
 * - text   -> span
 * - button -> button
 * - others -> div
 * Custom components are currently treated as normal container nodes.
 * @param {object} vnode
 * @param {Worker} worker
 * @returns {Node}
 */
export function createEl(vnode, worker) {
  let el;

  if (vnode.type === "#text") {
    el = document.createTextNode(vnode.value ?? "");
    vnode.el = el;
    return el;
  }

  if (vnode.type === "view") {
    el = document.createElement("div");
  } else if (vnode.type === "text") {
    el = document.createElement("span");
  } else if (vnode.type === "button") {
    el = document.createElement("button");
  } else {
    el = document.createElement("div");
  }

  setProps(el, vnode.props || {});
  bindEvents(el, vnode, worker);

  vnode.el = el;
  return el;
}